name: changeset-release
description: Executes the required changeset scripts to create a new 'Version' PR or publish to npm.

inputs:
  npm-token:
      description: 'The npm token used for publishing design system packages.'
      required: true
  github-token:
      description: 'The github token used for creating version PRs & tagging.'

runs:
  using: composite
  steps:
  - name: Check for pre.json file existence
    id: check_files
    uses: andstor/file-existence-action@v2.0.0
    with:
      files: ".changeset/pre.json"
  - name: exit prerelease mode
    shell: bash
    # If .changeset/pre.json does not exist and we did not recently exit
    # prerelease mode.
    if: steps.check_files.outputs.files_exists == 'true' && contains(github.ref_name, 'main')
    run: npx changeset pre exit
  - name: Create latest release PR
    if: contains(github.ref_name, 'main')
    uses: changesets/action@v1
    with:
      version: yarn changeset:version
      publish: yarn changeset:publish
      commit: "release: release packages with 'latest' tag"
  # If .changeset/pre.json does not exist and we did not recently exit
  # prerelease mode, enter prerelease mode with tag beta
  - name: Enter beta prerelease mode
    shell: bash
    if: steps.check_files.outputs.files_exists == 'false' && contains(github.ref_name, 'beta')
    # If .changeset/pre.json does not exist and we did not recently exit
    # prerelease mode, enter prerelease mode with tag beta
    run: npx changeset pre enter beta
  - name: Create beta release PR
    if: contains(github.ref_name, 'beta')
    uses: changesets/action@v1
    with:
      version: yarn changeset:version
      publish: yarn changeset:publish
      commit: "release: release packages with 'beta' tag"
  - name: Enter feature prerelease mode
    shell: bash
    if: steps.check_files.outputs.files_exists == 'false' && contains(github.ref_name, 'feature')
    # If .changeset/pre.json does not exist and we did not recently exit
    # prerelease mode, enter prerelease mode with tag next
    run: npx changeset pre enter next
  - name: Create feature release PR
    if: contains(github.ref_name, 'feature')
    uses: changesets/action@v1
    with:
      version: yarn changeset:version
      publish: yarn changeset:publish
      commit: "release: release packages with 'next' tag"
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      npm-token: ${{ inputs.npm-token }}
