/**
 * Reads @justeat/pie-design-tokens/dist/tokens.json and generates
 * typed token maps in src/generated/.
 *
 * Run: yarn generate
 */

import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENERATED_DIR = resolve(__dirname, '../src/generated');

// eslint-disable-next-line @typescript-eslint/no-var-requires
const tokens = require('@justeat/pie-design-tokens/dist/tokens.json');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const tokensPkg = require('@justeat/pie-design-tokens/package.json');

const HEADER = '// Auto-generated by scripts/generate-token-map.ts — do not edit manually.\n';

/**
 * Returns true if a property key needs quoting (contains hyphens, starts with a digit, etc.).
 */
function needsQuotes (key: string): boolean {
    return !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

/**
 * Format a property key, quoting only when necessary.
 */
function formatKey (key: string): string {
    return needsQuotes(key) ? `'${key}'` : key;
}

function writeFile (filePath: string, content: string): void {
    writeFileSync(filePath, content, 'utf-8');
    // eslint-disable-next-line no-console
    console.info(`  Generated ${filePath}`);
}

/**
 * Generate a simple map where each token name maps to a single CSS var ref.
 */
function generateSimpleMap (
    names: string[],
    prefix: string,
    typeName: string,
    mapName: string,
    namesArrayName: string,
): string {
    const sorted = [...names].sort();
    const namesArr = sorted.map((n) => `    '${n}',`).join('\n');
    const entries = sorted.map((n) => `    ${formatKey(n)}: 'var(--dt-${prefix}-${n})',`).join('\n');

    return `${HEADER}import type { CssVarRef } from '../types.js';

export const ${namesArrayName} = [
${namesArr}
] as const;

export type ${typeName} = typeof ${namesArrayName}[number];

export const ${mapName}: Record<${typeName}, CssVarRef> = {
${entries}
};
`;
}

// ---------------------------------------------------------------------------
// Color map
// ---------------------------------------------------------------------------

/**
 * Platform-agnostic aliases for Android parity.
 * tokens.json uses `web-container-*` but the server sends `container-*`.
 */
const COLOR_ALIASES: Record<string, string> = {
    'container-base': 'web-container-base',
    'container-base-dark': 'web-container-base-dark',
    'container-neutral': 'web-container-neutral',
    'container-prominent': 'web-container-prominent',
};

/**
 * Platform-specific token prefixes that should be excluded from the web map.
 * These CSS custom properties are not output by pie-css, so they would silently
 * resolve to empty values if used on the web.
 */
const PLATFORM_SPECIFIC_PREFIXES = ['android-', 'ios-'];

function generateColorMap (): void {
    const colorNames: string[] = Object.keys(tokens.theme.jet.color.alias.default)
        .filter((name) => !PLATFORM_SPECIFIC_PREFIXES.some((prefix) => name.startsWith(prefix)));

    // Add platform-agnostic alias names
    const aliasNames = Object.keys(COLOR_ALIASES).filter((a) => !colorNames.includes(a));
    const allNames = [...colorNames, ...aliasNames];

    const sorted = [...allNames].sort();
    const namesArr = sorted.map((n) => `    '${n}',`).join('\n');
    const entries = sorted.map((n) => {
        // Aliases point to the web-prefixed CSS var
        const cssName = COLOR_ALIASES[n] || n;
        return `    ${formatKey(n)}: 'var(--dt-color-${cssName})',`;
    }).join('\n');

    const content = `${HEADER}import type { CssVarRef } from '../types.js';

export const colorTokenNames = [
${namesArr}
] as const;

export type ColorTokenName = typeof colorTokenNames[number];

export const colorMap: Record<ColorTokenName, CssVarRef> = {
${entries}
};
`;
    writeFile(resolve(GENERATED_DIR, 'color-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Typography map
// ---------------------------------------------------------------------------
function generateTypographyMap (): void {
    const fontTokens = tokens.theme.jet.font.alias as Record<string, Record<string, unknown>>;
    const names = Object.keys(fontTokens).sort();

    const namesArr = names.map((n) => `    '${n}',`).join('\n');

    const entries = names.map((name) => {
        const token = fontTokens[name];
        const isResponsive = 'size--wide' in token;
        const hasStyle = 'font-style' in token;
        const hasDecoration = 'text-decoration' in token;
        const hasParagraph = 'paragraph' in token;

        const prefix = `--dt-font-${name}`;
        const props: string[] = [
            `        family: 'var(${prefix}-family)',`,
            `        weight: 'var(${prefix}-weight)',`,
        ];

        if (isResponsive) {
            props.push(`        sizeWide: 'var(${prefix}-size--wide)',`);
            props.push(`        lineHeightWide: 'var(${prefix}-line-height--wide)',`);
            props.push(`        sizeNarrow: 'var(${prefix}-size--narrow)',`);
            props.push(`        lineHeightNarrow: 'var(${prefix}-line-height--narrow)',`);
        } else {
            props.push(`        size: 'var(${prefix}-size)',`);
            props.push(`        lineHeight: 'var(${prefix}-line-height)',`);
        }

        if (hasStyle) {
            props.push(`        fontStyle: 'var(${prefix}-font-style)',`);
        }
        if (hasDecoration) {
            props.push(`        textDecoration: 'var(${prefix}-text-decoration)',`);
        }
        if (hasParagraph) {
            props.push(`        paragraph: 'var(${prefix}-paragraph)',`);
        }

        return `    ${formatKey(name)}: {\n${props.join('\n')}\n    },`;
    }).join('\n');

    const content = `${HEADER}import type { TypographyTokenValue } from '../types.js';

export const typographyTokenNames = [
${namesArr}
] as const;

export type TypographyTokenName = typeof typographyTokenNames[number];

export const typographyMap: Record<TypographyTokenName, TypographyTokenValue> = {
${entries}
};
`;

    writeFile(resolve(GENERATED_DIR, 'typography-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Radius map
// ---------------------------------------------------------------------------
function generateRadiusMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.radius.alias);
    const content = generateSimpleMap(names, 'radius', 'RadiusTokenName', 'radiusMap', 'radiusTokenNames');
    writeFile(resolve(GENERATED_DIR, 'radius-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Spacing map
// ---------------------------------------------------------------------------
function generateSpacingMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.spacing.alias);
    const content = generateSimpleMap(names, 'spacing', 'SpacingTokenName', 'spacingMap', 'spacingTokenNames');
    writeFile(resolve(GENERATED_DIR, 'spacing-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Elevation map
// ---------------------------------------------------------------------------
function generateElevationMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.elevation.alias.default);
    const content = generateSimpleMap(names, 'elevation', 'ElevationTokenName', 'elevationMap', 'elevationTokenNames');
    writeFile(resolve(GENERATED_DIR, 'elevation-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Gradient map
// ---------------------------------------------------------------------------
function generateGradientMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.gradient.alias.default);
    const content = generateSimpleMap(names, 'gradient', 'GradientTokenName', 'gradientMap', 'gradientTokenNames');
    writeFile(resolve(GENERATED_DIR, 'gradient-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Motion map
// Note: Motion tokens only exist under `global` in tokens.json (there is no
// `alias` key for motion). Using `global` here is intentional and is the only
// available source for these tokens.
// ---------------------------------------------------------------------------
function generateMotionMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.motion.global);
    const content = generateSimpleMap(names, 'motion', 'MotionTokenName', 'motionMap', 'motionTokenNames');
    writeFile(resolve(GENERATED_DIR, 'motion-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Breakpoint map
// ---------------------------------------------------------------------------
function generateBreakpointMap (): void {
    const names: string[] = Object.keys(tokens.theme.jet.breakpoint.alias);
    const content = generateSimpleMap(names, 'breakpoint', 'BreakpointTokenName', 'breakpointMap', 'breakpointTokenNames');
    writeFile(resolve(GENERATED_DIR, 'breakpoint-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Z-index map (hand-written — values from pie-css/css/input.css, not tokens.json)
// ---------------------------------------------------------------------------
function generateZIndexMap (): void {
    const names = [
        'base',
        'bottom-sheet',
        'cookie-banner',
        'dropdown',
        'fab',
        'modal',
        'popover',
        'side-sheet',
        'toast',
        'tooltip',
    ];
    const content = generateSimpleMap(names, 'z-index', 'ZIndexTokenName', 'zIndexMap', 'zIndexTokenNames');
    writeFile(resolve(GENERATED_DIR, 'z-index-map.ts'), content);
}

// ---------------------------------------------------------------------------
// Version
// ---------------------------------------------------------------------------
function generateVersion (): void {
    const content = `${HEADER}export const tokensVersion = '${tokensPkg.version}';\n`;
    writeFile(resolve(GENERATED_DIR, 'version.ts'), content);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function main (): void {
    mkdirSync(GENERATED_DIR, { recursive: true });

    // eslint-disable-next-line no-console
    console.info('Generating token maps...');

    generateColorMap();
    generateTypographyMap();
    generateRadiusMap();
    generateSpacingMap();
    generateElevationMap();
    generateGradientMap();
    generateMotionMap();
    generateBreakpointMap();
    generateZIndexMap();
    generateVersion();

    // eslint-disable-next-line no-console
    console.info('Done.');
}

main();
