# Project organisation

# App projects
apps:
- 'apps/**/*'

pie-docs:
- 'apps/pie-docs/**/*'

pie-storybook:
- 'apps/pie-storybook/**/*'

# Tools projects
tools:
- 'packages/tools/**/*'

pie-icons:
- 'packages/tools/pie-icons/**/*'

pie-icons-react:
- 'packages/tools/pie-icons-react/**/*'

pie-icons-vue:
- 'packages/tools/pie-icons-vue/**/*'

stylelint-config-pie:
- 'packages/tools/stylelint-config-pie/**/*'

generator-pie-component:
- 'packages/tools/generator-pie-component/**/*'

pie-css:
- 'packages/tools/pie-css/**/*'

# Component projects
components:
- 'packages/components/**/*'

pie-button:
- 'packages/components/pie-button/**/*'

pie-divider:
- 'packages/components/pie-divider/**/*'

pie-link:
- 'packages/components/pie-link/**/*'

pie-modal:
- 'packages/components/pie-modal/**/*'

pie-icon-button:
- 'packages/components/pie-icon-button/**/*'

pie-webc-core:
- 'packages/components/pie-webc-core/**/*'

pie-webc-testing:
- 'packages/components/pie-webc-testing/**/*'
