# Project organisation

# App projects
apps:
  - 'apps/**/*'

ci:
  - '.github/**/*'

pie-docs:
  - 'apps/pie-docs/**/*'

pie-storybook:
  - 'apps/pie-storybook/**/*'

# Config projects
configs:
  - 'configs/**/*'

pie-components-config:
  - 'configs/pie-components-config/**/*'

# Tools projects
tools:
  - 'packages/tools/**/*'

pie-monorepo-utils:
  - 'packages/tools/pie-monorepo-utils/**/*'

pie-icons:
  - 'packages/tools/pie-icons/**/*'

pie-icons-react:
  - 'packages/tools/pie-icons-react/**/*'

pie-icons-vue:
  - 'packages/tools/pie-icons-vue/**/*'

browserslist-config-pie:
  - 'packages/tools/browserslist-config-pie/**/*'

eslint-config-pie:
  - 'packages/tools/eslint-config-pie/**/*'

stylelint-config-pie:
  - 'packages/tools/stylelint-config-pie/**/*'

generator-pie-component:
  - 'packages/tools/generator-pie-component/**/*'

pie-css:
  - 'packages/tools/pie-css/**/*'

# Component projects
components:
  - 'packages/components/**/*'

pie-assistive-text:
  - 'packages/components/pie-assistive-text/**/*'

pie-button:
  - 'packages/components/pie-button/**/*'

pie-card:
  - 'packages/components/pie-card/**/*'

pie-checkbox:
  - 'packages/components/pie-checkbox/**/*'

pie-checkbox-group:
  - 'packages/components/pie-checkbox-group/**/*'

pie-chip:
  - 'packages/components/pie-chip/**/*'

pie-cookie-banner:
  - 'packages/components/pie-cookie-banner/**/*'

pie-divider:
  - 'packages/components/pie-divider/**/*'

pie-form-label:
  - 'packages/components/pie-form-label/**/*'

pie-icon-button:
  - 'packages/components/pie-icon-button/**/*'

pie-link:
  - 'packages/components/pie-link/**/*'

pie-lottie-player:
  - 'packages/components/pie-lottie-player/**/*'

pie-modal:
  - 'packages/components/pie-modal/**/*'

pie-notification:
  - 'packages/components/pie-notification/**/*'

pie-radio:
  - 'packages/components/pie-radio/**/*'

pie-radio-group:
  - 'packages/components/pie-radio-group/**/*'

pie-spinner:
  - 'packages/components/pie-spinner/**/*'

pie-switch:
  - 'packages/components/pie-switch/**/*'

pie-tag:
  - 'packages/components/pie-tag/**/*'

pie-text-input:
  - 'packages/components/pie-text-input/**/*'

pie-textarea:
  - 'packages/components/pie-textarea/**/*'

pie-toast:
  - 'packages/components/pie-toast/**/*'

pie-webc:
  - 'packages/components/pie-webc/**/*'

pie-webc-core:
  - 'packages/components/pie-webc-core/**/*'

pie-webc-testing:
  - 'packages/components/pie-webc-testing/**/*'