# Project organisation

# App projects
apps:
- 'apps/**/*'

pie-docs:
- 'apps/pie-docs/**/*'

pie-storybook:
- 'apps/pie-storybook/**/*'

# Tools projects
tools:
- 'packages/tools/**/*'

pie-icons:
- 'packages/tools/pie-icons/**/*'

pie-icons-react:
- 'packages/tools/pie-icons-react/**/*'

pie-icons-vue:
- 'packages/tools/pie-icons-vue/**/*'

browserslist-config-pie:
- 'packages/tools/browserslist-config-pie/**/*'

eslint-config-pie:
- 'packages/tools/eslint-config-pie/**/*'

stylelint-config-pie:
- 'packages/tools/stylelint-config-pie/**/*'

generator-pie-component:
- 'packages/tools/generator-pie-component/**/*'

pie-css:
- 'packages/tools/pie-css/**/*'

# Component projects
components:
- 'packages/components/**/*'

pie-button:
- 'packages/components/pie-button/**/*'

pie-card:
- './packages/components/pie-card/**/*'

pie-cookie-banner:
- './packages/components/pie-cookie-banner/**/*'

pie-chip:
- './packages/components/pie-chip/**/*'

pie-divider:
- 'packages/components/pie-divider/**/*'

pie-form-label:
- 'packages/components/pie-form-label/**/*'

pie-icon-button:
- 'packages/components/pie-icon-button/**/*'

pie-input:
- "packages/components/pie-input/**/*"

pie-link:
- 'packages/components/pie-link/**/*'

pie-modal:
- 'packages/components/pie-modal/**/*'

pie-notification:
- 'packages/components/pie-notification/**/*'

pie-switch:
- 'packages/components/pie-switch/**/*'

pie-spinner:
- "packages/components/pie-spinner/**/*"

pie-tag:
- "packages/components/pie-tag/**/*"

pie-webc-core:
- 'packages/components/pie-webc-core/**/*'

pie-webc-testing:
- 'packages/components/pie-webc-testing/**/*'
