compressionLevel: mixed

enableGlobalCache: true
enableHardenedMode: false

nodeLinker: node-modules

packageExtensions:
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: 8
  stylelint-config-standard-scss@*:
    peerDependencies:
      postcss: 8
