name: enivronment-teardown
description: Teardown preview after merge

inputs:
  amplify-app-id:
    description: 'The ID for your app which you can get from the end of its ARN'
    required: true
  aws-region:
    description: 'The AWS region from which to tear down your app'
    required: true
  aws-access-key-id:
    description: 'The AWS Access Key for the account that hosts your app'
    required: true
  aws-secret-access-key:
    description: 'The AWS Secret Access Key for the account that hosts your app'
    required: true
  environment-name:
    description: 'GitHub environment name to delete'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true
  gh-app-id:
    description: 'The ID of your GitHub app (used to generate a JWT for environment deletion)'
    required: true
  gh-app-private-key:
    description: 'The SSH private key for your GitHub app (used to generate a JWT for environment deletion)'
    required: true

runs:
  using: composite
  steps:
  - name: 🎟 Get GitHub App token
    uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681 # v1.2.1 
    id: get-token
    with:
      app-id: ${{ inputs.gh-app-id }}
      private-key: ${{ inputs.gh-app-private-key }}

  - name: Delete associated GitHub environment
    uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
    with:
      # Use a JWT created with your GitHub App's private key
      token: ${{ steps.get-token.outputs.token }}
      environment: ${{ inputs.environment-name }}

  - name: Delete Amplify branch
    shell: bash
    env:
      APP_ID: ${{ inputs.amplify-app-id }}
      BRANCH_NAME: ${{ inputs.branch-name }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_REGION: ${{ inputs.aws-region }}
    run: |
      aws amplify delete-branch \
        --app-id "$APP_ID" \
        --branch-name "$BRANCH_NAME"