name: enivronment-teardown
description: Teardown preview after merge

inputs:
  github-token:
    description: 'The GitHub token for the account that hosts your app'
    required: true
  amplify-app-id:
    description: 'The ID for your app which you can get from the end of its ARN'
    required: true
  aws-region:
    description: 'The AWS region from which to tear down your app'
    required: true
  aws-access-key-id:
    description: 'The AWS Access Key for the account that hosts your app'
    required: true
  aws-secret-access-key:
    description: 'The AWS Secret Access Key for the account that hosts your app'
    required: true
  environment-name:
    description: 'GitHub environment name to delete'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true

runs:
  using: composite
  steps:
  - name: Delete associated GitHub environment
    uses: actions/github-script@v6
    with:
      script: |
        const owner = context.repo.owner;
        const repo = context.repo.repo;
        const envName = ${{ inputs.environment-name }};

        try {
          await github.rest.repos.deleteAnEnvironment({
            owner: owner,
            repo: repo,
            environment_name: envName,
          });
          console.log(`Environment ${envName} deleted successfully.`);
        } catch (err) {
          console.log(`Failed to delete environment ${envName} with error: ${err}`);
        }
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}

  - name: Delete Amplify branch
    shell: bash
    run: |
      aws amplify delete-branch \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_REGION: ${{ inputs.aws-region }}
