name: run-script
description: Executes a package.json script for the monorepo or individual package.

inputs:
  script-name:
    description: 'The name of the package.json script to execute.'
    required: true
  concurrency:
    description: 'The number of concurrent scripts to execute.'
    required: false

runs:
  using: composite
  steps:
    - name: Run ${{ inputs.script-name }}
      shell: bash
      env:
        SCRIPT_NAME: ${{ inputs.script-name }}
        CONCURRENCY: ${{ inputs.concurrency }}
      run: |
        CONCURRENCY_FLAG=""

        if [ ! -z "$CONCURRENCY" ]; then
          CONCURRENCY_FLAG="--concurrency=$CONCURRENCY"
        fi

        yarn "$SCRIPT_NAME "$CONCURRENCY_FLAG"
