name: run-script
description: Executes a package.json script for the monorepo or individual package.

inputs:
  script-name:
    description: 'The name of the package.json script to execute.'
    required: true
  concurrency:
    description: 'The number of concurrent scripts to execute.'
    required: false

runs:
  using: composite
  steps:
    - name: Run ${{ inputs.script-name }}
      shell: bash
      run: |
        CONCURRENCY_FLAG=""

        if [ ! -z "${{ inputs.concurrency }}" ]; then
          CONCURRENCY_FLAG="--concurrency=${{ inputs.concurrency }}"
        fi

        yarn ${{ inputs.script-name }} $CONCURRENCY_FLAG --color
