name: setup-repo
description: Sets up the repo

inputs:
  node-version:
    description: 'The node version required for the GitHub action job.'
    required: true
  os:
    description: 'The operating system required for the GitHub action job.'
    required: true

runs:
  using: composite
  steps:
      - name: Get caching params
        id: cache-params
        shell: bash
        run: |
          echo "::group::Cache params"
          echo "Getting cache params"
          echo "node-version=$(node -v)" >> "$GITHUB_OUTPUT"
          node -v
          echo "yarn-version=$(yarn -v)" >> "$GITHUB_OUTPUT"
          yarn -v
          echo "yarn-cache-path=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
          yarn config get cacheFolder
          echo "yarn-global-path=$(yarn config get globalFolder)" >> "$GITHUB_OUTPUT"
          yarn config get globalFolder
          echo "yarn-virtual-path=$(yarn config get virtualFolder)" >> "$GITHUB_OUTPUT"
          yarn config get virtualFolder
          echo "yarn-state-path=$(yarn config get installStatePath)" >> "$GITHUB_OUTPUT"
          yarn config get installStatePath
          echo "::endgroup::"

      # Restore yarn package cache and build cache - specific key for each os/arch/node version
      - name: Yarn cache and build state
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ steps.cache-params.outputs.yarn-cache-path }}
            ${{ steps.cache-params.outputs.yarn-global-path }}
            ${{ steps.cache-params.outputs.yarn-virtual-path }}
            ${{ steps.cache-params.outputs.yarn-state-path }}
          key: yarn-${{ runner.os }}-${{ runner.arch }}-node-${{ steps.cache-params.outputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-${{ runner.arch }}-node-${{ steps.cache-params.outputs.node-version }}-

      - name: Install Dependencies
        shell: bash
        run: yarn install --immutable
