name: setup-repo
description: Sets up the repo

inputs:
  node-version:
    description: 'The node version required for the GitHub action job.'
    required: true
  os:
    description: 'The operating system required for the GitHub action job.'
    required: true

runs:
  using: composite
  steps:
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
      # Run 'yarn' if cache doesn't exist. Use --prefer-offline to download packages from yarn cache folder where possible
      - name: Install Dependencies
        shell: bash
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn add
