name: setup-repo
description: Sets up the repo

inputs:
  node-version:
    description: 'The node version required for the GitHub action job.'
    required: true
  os:
    description: 'The operating system required for the GitHub action job.'
    required: true

runs:
  using: composite
  steps:
      # Setup Node
      - name: Setup Node
        id: cache-node-modules
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: "yarn"
          cache-dependency-path: ${{ github.workspace }}/yarn.lock
          node-version: ${{ inputs.node-version }}
          path: ${{ github.workspace }}/node_modules
      # Run 'yarn' if cache doesn't exist. Use --prefer-offline to download packages from yarn cache folder where possible
      - name: Install Dependencies
        shell: bash
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn add
