import React, { useState } from 'react';
import Head from 'next/head'
import { createComponent } from '@lit-labs/react';
import { PieButton, BUTTON_SIZE, BUTTON_VARIANT } from '@justeattakeaway/pie-button';

// Module parse failed: Unexpected token (4:7)
// You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
// import { BUTTON_SIZE, BUTTON_VARIANT } from '@justeattakeaway/pie-button/src/defs';

// eslint-disable-next-line no-unused-vars
const Button = createComponent({
    tagName: 'pie-button',
    elementClass: PieButton,
    react: React,
    events: { onCustomEvent: 'CustomEvent' },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button size='large' />
        <Button variant='secondary' />
        <Button disabled />
      </main>
    </>
  )
}
