#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#Check commit message format
npx --no -- commitlint --edit ${1}

# Adds Jira ticket id to commit message
packages/tools/pie-git-hooks-scripts/check-ticket-id.js $1 $(git symbolic-ref --short HEAD)

# Section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialise git-secrets configuration
git-secrets --register-aws > /dev/null

echo "Checking commit message for secrets..."
# Scans the commit message.
git-secrets --commit_msg_hook -- "$@"
echo "Checking commit message for secrets...DONE"
