#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Checks branch name for Jira ticket id
packages/tools/git-hooks-scripts/check-branch-name.js $(git symbolic-ref --short HEAD)

# Heavy checks should only be done on staged files
yarn eslint $(git diff --name-only HEAD HEAD~1 | grep -E '\.(js|jsx)$' | xargs) --max-warnings 0