#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Checks branch name for Jira ticket id
packages/tools/pie-git-hooks-scripts/check-branch-name.js $(git symbolic-ref --short HEAD)

# Section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialise git-secrets configuration
git-secrets --register-aws > /dev/null

echo "Running git-secrets..."
# Scans all files that are about to be committed.
git-secrets --pre_commit_hook -- "$@"

# Ensure `yarn.lock` is updated
echo "Installing dependencies to update yarn.lock if necessary..."
yarn install # This will update the `yarn.lock` file if dependencies have changed

# Check if `yarn.lock` was modified
if [ -n "$(git status --porcelain yarn.lock)" ]; then
    echo "yarn.lock was updated. Staging the file..."
    git add yarn.lock
fi
