#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Checks branch name for Jira ticket id
packages/tools/git-hooks-scripts/check-branch-name.js $(git symbolic-ref --short HEAD)

# Checks the diff files for lint errors before allowing to push
yarn lint:scripts