#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

echo "Checking history for secrets..."
git-secrets --prepare_commit_msg_hook -- "$@"
echo "Checking history for secrets...DONE"

