name: setup-playwright
description: Sets up playwright in repo

runs:
  using: composite
  steps:
      - name: Get installed Playwright version
        shell: bash
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=`node -p "require('./package.json')['devDependencies']['@playwright/test']"`" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.playwright_version }}
      - run: npx playwright install --with-deps
        shell: bash
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        shell: bash
