name: Version / Release Beta packages

on:
  push:
    branches:
      - beta-*

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  beta-release:
    name: Beta Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        # Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      # Restore node_modules if cache exists. If not, cache is created at end of build.
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      # Run 'yarn' if cache doesn't exist. Use --prefer-offline to download packages from yarn cache folder where possible
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn add --cached
      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".changeset/pre.json"
      - name: Enter beta prerelease mode
        # If .changeset/pre.json does not exist and we did not recently exit
        # prerelease mode, enter prerelease mode with tag beta
        if: steps.check_files.outputs.files_exists == 'false'
        run: npx changeset pre enter beta
      - name: Create beta release PR
        uses: changesets/action@v1
        with:
          version: npx changeset version
          commit: ":test_tube: Version Packages with 'beta' tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}