name: CI - Web Components & Storybook

on:
  workflow_call:
  push:
    branches:
      - main

concurrency:
  group: CI-WebComponents-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  PERCY_TOKEN_PIE_BUTTON: ${{ secrets.PERCY_TOKEN_PIE_BUTTON }}
  PERCY_TOKEN_PIE_CARD: ${{ secrets.PERCY_TOKEN_PIE_CARD }}
  PERCY_TOKEN_PIE_COOKIE_BANNER: ${{ secrets.PERCY_TOKEN_PIE_COOKIE_BANNER }}
  PERCY_TOKEN_PIE_FORM_LABEL: ${{ secrets.PERCY_TOKEN_PIE_FORM_LABEL }}
  PERCY_TOKEN_PIE_DIVIDER: ${{ secrets.PERCY_TOKEN_PIE_DIVIDER }}
  PERCY_TOKEN_PIE_ICON_BUTTON: ${{ secrets.PERCY_TOKEN_PIE_ICON_BUTTON }}
  PERCY_TOKEN_PIE_LINK: ${{ secrets.PERCY_TOKEN_PIE_LINK }}
  PERCY_TOKEN_PIE_MODAL: ${{ secrets.PERCY_TOKEN_PIE_MODAL }}
  PERCY_TOKEN_PIE_NOTIFICATION: ${{ secrets.PERCY_TOKEN_PIE_NOTIFICATION }}
  PERCY_TOKEN_PIE_SWITCH: ${{ secrets.PERCY_TOKEN_PIE_SWITCH }}
  PERCY_TOKEN_PIE_SPINNER: ${{ secrets.PERCY_TOKEN_PIE_SPINNER }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Repo
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: 20
          os: ubuntu-latest
      # Lint Styles
      - name: Lint Styles
        uses: ./.github/actions/run-script
        with:
          script-name: "lint:style --filter='./packages/{components,tools}/*'"
          concurrency: 10
      # Lint JS
      - name: Lint JavaScript
        uses: ./.github/actions/run-script
        with:
          script-name: "lint:scripts --filter='./packages/{components,tools}/*'"
          concurrency: 10

  build-ubuntu-node-20:
    uses: ./.github/workflows/install-build.yml
    needs: lint
    with:
      os: ubuntu-latest
      node-version: 20
    secrets: inherit

  unit-tests:
    needs: 'build-ubuntu-node-20'
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Repo
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: 20
          os: ubuntu-latest
      # Restore Packages from Cache
      - name: Build Packages
        uses: ./.github/actions/run-script
        with:
          script-name: "build --filter='./packages/{components,tools}/*"
      # Run Unit Tests
      - name: Unit Tests
        uses: ./.github/actions/run-script
        with:
          script-name: "test:ci --filter='./packages/{components,tools}/*"

  # TODO: DSW-1151 - Move this into a reusable action so it's not duplicated
  browser-tests-components:
    needs: build-ubuntu-node-20
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup Repo
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: 20
          os: ubuntu-latest
      # Setup Playwright
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
      # Run System / a11y Tests
      - name: Run All System / Component /  a11y Tests
        uses: ./.github/actions/run-script
        with:
          script-name: "test:browsers:ci --filter='./packages/components/*'"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: browsers-report
          path: browsers-report/
          retention-days: 7
      # Run Visual Tests
      - name: Run All Visual Tests
        uses: ./.github/actions/run-script
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          script-name: "test:visual:ci --filter='{./packages/components/*}[HEAD^1]'"
          concurrency: 1
      - name: Run Changed Package Visual Tests
        uses: ./.github/actions/run-script
        if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false) && github.ref != 'refs/heads/main'
        with:
          script-name: "test:visual:ci --filter='{./packages/components/*}[origin/main]'"
          concurrency: 1
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: visual-report
          path: visual-report/
          retention-days: 7

  deploy-storybook:
    needs: unit-tests
    uses: ./.github/workflows/amplify-deploy.yml
    with:
      os: ubuntu-latest
      node-version: 20
      amplify-app-id: d17ja0ul7nrdy0
      package-name: 'pie-storybook'
      package-dist-directory: ./apps/pie-storybook/dist
      bucket-name-preview: 'pie-storybook-preview'
      bucket-name-main: 'pie-storybook'
    secrets: inherit