name: DangerJS PR Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  danger-checks:
    if: ${{ github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate GitHub App token
        id: get-token
        uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681 # v1.2.1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      # Setup Repo
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: 24
          os: ubuntu-latest
      # Run Danger Checks
      - name: Danger
        run: yarn danger ci --failOnErrors
        env:
          DANGER_GITHUB_API_TOKEN: ${{ steps.get-token.outputs.token }}
