name: Install and Build Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build-script:
        required: false
        type: string
        default: 'build'
      analyse-component-bundles:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  install-build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          os: ${{ inputs.os }}
      - name: Build Packages
        uses: ./.github/actions/run-script
        with:
          script-name: ${{ inputs.build-script }}
      - name: Analyse Component Bundle Sizes
        if: inputs.analyse-component-bundles
        run: yarn analyse-component-bundles
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          CI_BRANCH_BASE: 'main'
