name: Pull Request Labeler
on:
  workflow_run:
    workflows: ["Gather PR Info"]
    types:
      - completed

jobs:
  process-info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: pr-info

    # Process the information and perform actions that require secrets
    - name: Add Missing Labels
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
      with:
        github-token: ${{ secrets.CHANGESETS_TOKEN }}
        script: |
          const fs = require('fs');
          const prInfo = fs.readFileSync('pr-info.txt', 'utf8');
          const prBranchName = prInfo.match(/PR_BRANCH_NAME=(.*)/)[1];
          const script = require('./.github/workflows/add-missing-labels/add-missing-labels.js');
          await script({ github, context, prBranchName });