name: Labeler - Set PR labels
on:
  workflow_run:
    workflows: [Labeler - Get PR labels]
    types:
      - completed

jobs:
  set-missing-labels:
    permissions:
      actions: read # For downloading artifacts
      contents: read # For accessing repository files
      pull-requests: write # For assigning a label to a PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download artifact and set labels
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/labeler/set-labels.js');
            await script({ github, context });
