name: Pull Request Labeler
on: pull_request_target
# By default, pull_request_target runs when the activity type is opened, synchronize, or reopened
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target

jobs:
  categorise:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Labeler
      uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
      with:
        configuration-path: '.github/project-labeler.yml'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        # Category labels will be removed if they no longer apply
        sync-labels: true
