name: Pull Request Labeler
on: pull_request_target
# By default, pull_request_target runs when the activity type is opened, synchronize, or reopened
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target

jobs:
  categorise:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Add Missing Labels
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
      with:
        github-token: ${{ secrets.CHANGESETS_TOKEN }}
        script: |
          const script = require('./.github/workflows/add-missing-labels/add-missing-labels.js')
          await script({ github, context });

    - name: Labeler
      uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
      with:
        configuration-path: '.github/project-labeler.yml'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        # Category labels will be removed if they no longer apply
        sync-labels: true
