name: Lighthouse CI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string
      environment-url:
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: ${{ inputs.node-version }}
          os: ${{ inputs.os }}

      - name: Get audit urls
        id: audit-urls
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const targetUrl = '${{ inputs.environment-url }}';
            const testPaths = require('./apps/pie-docs/test/snapshots/expected-routes.snapshot.json');
            const testUrls = testPaths.map(testPath => `${targetUrl}${testPath}`);
            core.setOutput("urls", [targetUrl, ...testUrls].join('\n'));
    
      - name: Audit URLs using Lighthouse
        id: audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: ${{ steps.audit-urls.outputs.urls }}

