name: Lighthouse CI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string
      environment-url:
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          node-version: ${{ inputs.node-version }}
          os: ${{ inputs.os }}

      - name: Load URLs from JSON
        id: load-urls
        run: |
          HOST_URL="${{ inputs.environment-url }}"
          URLS=(jq -r '.[]' < ./apps/pie-docs/test/snapshots/expected-routes.snapshot.json | while read path; do echo "$HOST_URL/$path"; done)
          echo "::set-output name=urls::$URLS"

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.load-urls.outputs.urls }}
