
 

name: Lint Github Workflows

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: [ self-hosted, ubuntu-latest ]
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'ci') && (github.event.repository.fork == false || github.event_name == 'pull_request')
    steps:

    - name: Checkout code
      # v4.1.7
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Lint workflows
      shell: bash
      env:
        ACTIONLINT_VERSION: 'v1.6.27'
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        bash <(curl --silent --show-error "https://raw.githubusercontent.com/rhysd/actionlint/${ACTIONLINT_VERSION}/scripts/download-actionlint.bash")
        ./actionlint -color