name: Merged

on:
  pull_request:
    types:
      # There is no `merged` event type, so we have to use `closed`
      # and then specify merged using the `if` below.
      - closed

env:
  DOCS_AMPLIFY_ID: dvskdcoepjoyf
  STORYBOOK_AMPLIFY_ID: d17ja0ul7nrdy0
  PR_NUMBER: ${{ github.event.number }}

jobs:
  merged:
    # Only run the job for merged PRs, not closed ones
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3
      # Tear down docs preview
      - name: Amplify Teardown (Docs)
        uses: ./.github/amplify-teardown
        with:
          amplify-app-id: ${{ env.DOCS_AMPLIFY_ID }}
          aws-region: 'eu-west-1'
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          branch-name: 'pr${{ github.event.number }}'
          bucket-name: ${{ secrets.AWS_DOCS_BUCKET }}
          package-name: 'pie-docs'
      # Tear down storybook preview
      - name: Amplify Teardown (Storybook)
        uses: ./.github/amplify-teardown
        with:
          amplify-app-id: ${{ env.STORYBOOK_AMPLIFY_ID }}
          aws-region: 'eu-west-1'
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          branch-name: 'pr${{ github.event.number }}'
          bucket-name: '${{ secrets.AWS_STORYBOOK_BUCKET }}'
          package-name: 'pie-storybook'
