# Project organisation

# App projects
apps:
- 'apps/**/*'

pie-microsite:
- 'apps/pie-microsite/**/*'

# Tools projects
tools:
- 'packages/tools/**/*'

pie-icons:
- 'packages/tools/pie-icons/**/*'

pie-icons-react:
- 'packages/tools/pie-icons-react/**/*'

pie-icons-vue:
- 'packages/tools/pie-icons-vue/**/*'

pie-stylelint-config:
- 'packages/tools/pie-stylelint-config/**/*'

# Component projects
components:
- 'packages/components/**/*'

pie-button:
- 'packages/components/pie-button/**/*'
