name: Update icons
on:
  workflow_dispatch:

env:
  HUSKY: 0
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

permissions:
  contents: read

jobs:
  update-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: get-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Setup Repo
        uses: ./.github/actions/setup-repo
        with:
          os: ubuntu-latest

      - name: Update icons
        run: yarn workspace @justeattakeaway/pie-icons update-icons

      - name: Create PR
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }} # this is set by the previous step
          CHANGESET_FILE_PATH: ${{ env.CHANGESET_FILE_PATH }} # this is set by the previous step
        with:
          github-token: ${{ steps.get-token.outputs.token }}
          script: |
            const script = require('./packages/tools/pie-monorepo-utils/create-icons-update-pr/create-icons-update-pr.js');
            const { BRANCH_NAME, CHANGESET_FILE_PATH } = process.env
            const config = {
              github,
              branchName: BRANCH_NAME,
              changesetFilePath:CHANGESET_FILE_PATH
            };
            await script(config);
