name: amplify-deploy
description: deploy to amplify

inputs:
  amplify-app-id:
    description: "The ID for your Amplify app (which you can get from the end of its ARN)"
    required: true
  aws-region:
    description: "The AWS region to deploy your Amplify app to"
    required: true
  aws-access-key-id:
    description: "The access key for the AWS account where your Amplify app is hosted"
    required: true
  aws-secret-access-key:
    description: "The secret access Key associated with your AWS account"
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true
  bucket-name:
    description: "The name of the S3 bucket containing your zipped website"
    required: true
  package-name:
    description: "Name of the application being deployed"
    required: true

runs:
  using: composite
  steps:
    # Zip dist folder
    - name: Zip build output
      shell: bash
      run: |
        cd apps/${{ inputs.package-name }}/dist
        zip -r ../../../${{ inputs.package-name }}-pr-${{github.event.number}}.zip .
    # Upload zip as Github Action artifact
    - name: Upload artifact to Github
      id: upload-github
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.package-name }}-pr-${{github.event.number}}
        path: ${{ inputs.package-name }}-pr-${{github.event.number}}.zip
        retention-days: 7
    # Upload zip to S3
    - name: Upload to S3
      id: upload-s3
      uses: hkusu/s3-upload-action@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        aws-bucket: ${{ inputs.bucket-name }}
        bucket-root: "/"
        destination-dir: "/"
        file-path: "./${{ inputs.package-name }}-pr-${{github.event.number}}.zip"
        content-type: "application/zip"
        public: true
    # Create branch on Amplify
    - name: Create Amplify branch
      shell: bash
      # We return true to prevent the step from failing if the branch already exists
      run: |
        aws amplify create-branch \
          --app-id ${{ inputs.amplify-app-id }} \
          --branch-name ${{ inputs.branch-name }} \
          || true
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    # Deploy Amplify from S3
    - name: Deploy Amplify from S3
      shell: bash
      run: |
        aws amplify start-deployment \
          --app-id ${{ inputs.amplify-app-id }} \
          --branch-name ${{ inputs.branch-name }} \
          --source-url https://${{ inputs.bucket-name }}.s3.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.package-name }}-pr-${{ github.event.number }}.zip \
          --debug
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
