name: amplify-deploy
description: deploy to amplify

inputs:
  amplify-app-id:
    description: 'The ID for your Amplify app which you can get from the end of its ARN'
    required: true
  aws-region:
    description: 'The AWS region to deploy your Amplify app to'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true
  bucket-name:
    description: 'The name of the S3 bucket containing your zipped website'
    required: true
  package-name:
    description: 'Name for the generated build zip that will be uploaded to S3'
    required: true
  aws-access-key-id:
    description: 'The AWS key ID where your Amplify app is hosted'
    required: true
  aws-secret-access-key:
    description: 'The AWS Secret Access Key associated with your account'
    required: true

runs:
  using: composite
  steps:
  # this step will fail if the branch already exists
  # so we return 'true' to ensure it'll always pass.
  - name: create amplify env
    shell: bash
    run: |
      aws amplify create-branch \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }} \
        || true
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_REGION: ${{ inputs.aws-region }}
  - name: deploy amplify from s3
    shell: bash
    run: |
      aws amplify start-deployment \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }} \
        --source-url https://${{ inputs.bucket-name }}.s3.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.package-name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_REGION: ${{ inputs.aws-region }}
