name: amplify-deploy
description: deploy to amplify

inputs:
  amplify-app-id:
    description: 'The ID for your Amplify app (which you can get from the end of its ARN)'
    required: true
  aws-region:
    description: 'The AWS region to deploy your Amplify app to'
    required: true
  aws-access-key-id:
    description: 'The access key for the AWS account where your Amplify app is hosted'
    required: true
  aws-secret-access-key:
    description: 'The secret access Key associated with your AWS account'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true
  bucket-name:
    description: 'The name of the S3 bucket containing your zipped website'
    required: true
  package-name:
    description: 'Name of the application being deployed'
    required: true

runs:
  using: composite
  steps:
  # Deploy using file from S3
  # - name: Deploy Amplify from S3
  #   shell: bash
  #   run: |
  #     aws amplify start-deployment \
  #       --app-id ${{ inputs.amplify-app-id }} \
  #       --branch-name ${{ inputs.branch-name }} \
  #       --source-url https://${{ inputs.bucket-name }}.s3.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.package-name }}-pr-${{ github.event.number }}.zip
  #   env:
  #     AWS_REGION: ${{ inputs.aws-region }}
  #     AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
  #     AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
  # Download Github artifact
  - name: Download artifact
    id: download-artifact
    uses: actions/download-artifact@v3
    with:
      name: '${{ inputs.package-name }}-pr-${{github.event.number}}'
  # Debug
  - name: 'Echo download path'
    shell: bash
    run: echo ${{steps.download-artifact.outputs.download-path}}
  # Deploy Amplify
  - name: Deploy Amplify from Github
    shell: bash
    # source-url only has two slashes because download path already has a leading slash
    run: |
      aws amplify start-deployment \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }} \
        --source-url file://${{steps.download-artifact.outputs.download-path}}/${{ inputs.package-name }}-pr-${{github.event.number}}
    env:
      AWS_REGION: ${{ inputs.aws-region }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
