name: amplify-deploy
description: deploy to amplify

inputs:
  amplify-app-id:
    description: 'The ID for your Amplify app which you can get from the end of its ARN'
    required: true
  aws-region:
    description: 'The AWS region to deploy your Amplify app to'
    required: true
  aws-access-key-id:
    description: 'The AWS key ID where your Amplify app is hosted'
    required: true
  aws-secret-access-key:
    description: 'The AWS Secret Access Key associated with your account'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true
  bucket-name:
    description: 'The name of the S3 bucket containing your zipped website'
    required: true
  github-token:
    description: 'GitHub token used to create the deployment environment'
    required: true
  package-name:
    description: 'Name for the application being deployed'
    required: true

runs:
  using: composite
  steps:
  # Zip dist
  - name: Zip build output
    shell: bash
    run: |
      cd apps/${{ inputs.package-name }}/dist
      zip -r ../../../${{ inputs.package-name }}-pr-${{github.event.number}}.zip .
  # Deployments
  - name: Create GitHub deployment
    if: ${{ github.ref != 'refs/heads/main' }}
    uses: chrnorm/deployment-action@v2
    id: ${{ inputs.package-name }}-deploy
    with:
      token: ${{ inputs.github-token }}
      environment: "${{inputs.package-name}}-pr-${{github.event.number}}"
  - name: Upload S3
    uses: hkusu/s3-upload-action@v2
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: '${{ inputs.aws-region }}'
      aws-bucket: ${{ inputs.bucket-name }}
      bucket-root: '/'
      destination-dir: '/'
      file-path: './${{ inputs.package-name }}-pr-${{github.event.number}}.zip'
      content-type: 'application/zip'
  # this step will fail if the branch already exists
  # so we return 'true' to ensure it'll always pass.
  - name: create amplify env
    shell: bash
    run: |
      aws amplify create-branch \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }} \
        || true
  - name: deploy amplify from s3
    shell: bash
    run: |
      aws amplify start-deployment \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }} \
        --source-url https://${{ inputs.bucket-name }}.s3.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.package-name }}-pr-${{github.event.number}}.zip
  - name: Update deployment status (success)
    if: success()
    uses: chrnorm/deployment-status@v2
    with:
      token: ${{ inputs.github-token }}
      environment-url: https://pr-${{github.event.number}}.${{ inputs.amplify-app-id }}.amplifyapp.com
      deployment-id: ${{ steps.${{ inputs.package-name }}-deploy.outputs.deployment_id }}
      state: "success"
  - name: Update deployment status (failure)
    if: failure()
    uses: chrnorm/deployment-status@v2
    with:
      token: ${{ inputs.github-token }}
      environment-url: https://pr-${{github.event.number}}.${{ inputs.amplify-app-id }}.amplifyapp.com
      deployment-id: ${{ steps.${{ inputs.package-name }}-deploy.outputs.deployment_id }}
      state: "failure"
